# Generated by Django 2.1 on 2022-07-06 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20180411_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='kind_id',
            field=models.CharField(blank=True, db_index=True, help_text='考试唯一标识', max_length=32, null=True, verbose_name='考试id'),
        ),
    ]
