# Generated by Django 2.1 on 2022-07-06 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20220706_2130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='kind_id',
            field=models.CharField(blank=True, db_index=True, help_text='比赛唯一标识', max_length=32, null=True, verbose_name='比赛id'),
        ),
    ]
