# Generated by Django 2.1 on 2022-07-06 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_auto_20220706_2130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessEmailInfo',
        ),
    ]
