# Generated by Django 2.1 on 2022-07-07 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0014_businessemailinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BusinessEmailInfo',
        ),
    ]
